### ISSUE TITLE
No Global Bundle

### ISSUE THREAD

**Issue by brownrl** [wieni/wmsettings#10]
When wmsettings installs it makes a Global bundle. This has a problem. When you create model out of it then the word global and the class global all have issues. Have it create a bundle called "site".

**Comment by DieterHolvoet** [comment]
That shouldn't be a reason for this module to change the name of the included settings bundle. On most sites we fix this issue by creating a `GlobalSettings` model class and implementing a custom `bundleDeduceRegex` method.
