### ISSUE TITLE
Query on un-indexed column

### ISSUE THREAD

**Issue by spoit** [wieni/wmsettings#12]
We noticed in the slow query log that there is a recurring query on a non-indexed column:

(site: bruzzdev)

```sql
SELECT base_table.id AS id, base_table.id AS base_table_id
FROM 
settings base_table
INNER JOIN settings_field_data settings_field_data ON settings_field_data.id = base_table.id
WHERE settings_field_data.wmsettings_key LIKE 'global\\_settings' ESCAPE '\\';
```

Task at hand: solve by 

a. Add an index on that basefield (https://drupal.stackexchange.com/questions/221410/how-to-add-a-database-index-to-a-base-field)

b. cache the results of the query

Note: I don't know where that query happens. I suspect somewhere in wmsettings but that's not a given.

**Comment by DieterHolvoet** [comment]
This was added in `0.3.3`
